# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- README.md
- stack.yaml
ghc-options:
- -Wall
library:
  dependencies:
  - base >=4.5 && <5
  source-dirs: library
  exposed-modules:
  - Geodesy
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: ghc-panic-translateConPatVec-lookup
synopsis: Reproduce GHC panic, ticket 121585
description: Reproduce GHC panic, ticket 121585
category: Flight
license: BSD3
license-file: LICENSE.md
github: BlockScope/ghc-panic-12158
version: '0.1.0'
